name: Build and run short tests
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"] # Maybe also some other versions like 3.13
        os: [ubuntu-latest] # Maybe also macos-latest, windows-latest
    runs-on: ${{ matrix.os }}
    env:
      USER_PASSWORD: "does_not_matter" # GitHub action should run `sudo` without password
      HEIMDALL_HOSTNAME: "github-workflow" # Match the name under `benchmark/basic_performance/env_files/{hostname}.env`
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up dependencies
        uses: ./.github/actions/setup-heimdall
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Build basic performance bandwidth tests"
        run: uv run heimdall bench build basic bw

      - name: "Install deps of lockfree data structures benchmark"
        run: uv run heimdall bench install lockfree all

      - name: "Build lockfree data structures benchmark tests"
        run: uv run heimdall bench build lockfree all

  build-standalone:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"] # Maybe also some other versions like 3.13
        os: [ubuntu-latest] # Maybe also macos-latest, windows-latest
    runs-on: ${{ matrix.os }}
    env:
      USER_PASSWORD: "does_not_matter" # GitHub action should run `sudo` without password
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up dependencies
        uses: ./.github/actions/setup-heimdall
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build standalone heimdall binary
        run: make standalone
        shell: bash

      - name: "Build basic performance bandwidth tests"
        run: ./dist/heimdall bench build basic bw
